<a href="https://colab.research.google.com/github/Asmit-Dhakal/Machine_Learning/blob/master/00_pytorch_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.2.1+cu121


# **Introduction to Tensors**
Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
# Get tensor back as python int
scalar.ndim


0

In [4]:
# Vector
vector=torch.tensor([7,7])

In [5]:
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [11]:
 # matrix
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
matrix.ndim

2

In [15]:
matrix[1]
matrix.shape

torch.Size([2, 2])

In [16]:
# Tensor
tensor =torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [17]:
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
tensor.ndim
tensor.shape


torch.Size([1, 3, 3])

In [22]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])