In [2]:
import numpy as np


In [3]:
## Datatypes and attribyutes
  

In [4]:
a1=np.array([1,2,3,4])

In [5]:
AI

NameError: name 'AI' is not defined

In [6]:
a1

array([1, 2, 3, 4])

In [7]:
type(a1)

numpy.ndarray

In [8]:
numpy.ndarray

NameError: name 'numpy' is not defined

In [10]:
a2=np.array([[1,2.0,3.3],[4,5,6.5]])

In [11]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [14]:
a3=np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
             ],
             [
              [10,11,12],
              [13,14,15],
              [16,17,18]]
            ])

In [15]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [16]:
a3.shape


(2, 3, 3)

In [17]:
a1.ndim

1

In [18]:
a1.dtype

dtype('int64')

In [19]:
a3.dtypr

AttributeError: 'numpy.ndarray' object has no attribute 'dtypr'

In [20]:
a3.dtype

dtype('int64')

In [21]:
a1.size

4

In [22]:
import pandas as pd

In [26]:
df1=pd.DataFrame(a2)

In [27]:
df1

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# Creating array

In [30]:
sample_array=np.array([1,2,3])

In [31]:
sample_array

array([1, 2, 3])

In [33]:
ones=np.ones((2,3))

In [34]:
ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
zeros=np.zeros((2,3))

In [36]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
range_array=np.arange(2,10,2)

In [42]:
range_array

array([2, 4, 6, 8])

In [44]:
random_array=np.random.randint(0,10,size=(3,5))

In [45]:
random_array

array([[8, 0, 8, 2, 9],
       [6, 3, 0, 6, 3],
       [3, 7, 3, 6, 8]])

In [46]:
random_shape

NameError: name 'random_shape' is not defined

In [47]:
random_array.shape

(3, 5)

In [ ]:
np_random array_2=np.random.random((5))